# Tensors and Shapes

## reduction

In [1]:
import numpy as np

a_shape = (4, 3, 2)
a_len= 4 * 3 * 2

a = np.arange(a_len).reshape(a_shape)

print(a.shape)
print(a)

(4, 3, 2)
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [2]:
b = np.sum(a, axis=0)
print(b.shape)
print(b)

(3, 2)
[[36 40]
 [44 48]
 [52 56]]


In [3]:
c = np.any(a > 4, axis=1)
print(c.shape)
print(c)

(4, 2)
[[False  True]
 [ True  True]
 [ True  True]
 [ True  True]]


In [4]:
d = np.product(a, axis=(2, 1))
print(d.shape)
print(d)

(4,)
[       0   332640  8910720 72681840]


## broadcasting 

In [5]:
a.shape

(4, 3, 2)

In [6]:
b = np.ones((4, 3, 2))
b.shape

(4, 3, 2)

In [7]:
c = a * b
c.shape

(4, 3, 2)

## modifying rank

In [9]:
a = np.ones((1, 4))
b = np.ones(
    16,
)
result = a + b[:, np.newaxis]
result.shape

(16, 4)

In [10]:
a = np.ones((1, 32, 4, 1))
print("before squeeze:", a.shape)
a = np.squeeze(a)
print("after squeeze:", a.shape)

before squeeze: (1, 32, 4, 1)
after squeeze: (32, 4)


In [12]:
a = np.ones((1, 4))
b = np.ones(
    16,
)
result = a + b[:, None]
result.shape

(16, 4)

## Modifying rank


### reshaping

In [13]:
a = np.arange(32)
new_a = np.reshape(a, (4, 8))
new_a.shape

(4, 8)

In [14]:
new_a = np.reshape(a, (4, -1))
new_a.shape

(4, 8)

In [15]:
new_a = np.reshape(a, (1, 2, 2, -1))
new_a.shape

(1, 2, 2, 8)

### rank slicing

In [16]:
def eq(a, b):
    return np.exp((a[..., np.newaxis] - b) ** 2)


b = np.ones(4)
a1 = np.ones((4, 3))
a2 = np.ones((4, 3, 2, 1))

g1 = eq(a1, b)
print("input a1:", a1.shape, "output:", g1.shape)

g2 = eq(a2, b)
print("input a2:", a2.shape, "output:", g2.shape)

input a1: (4, 3) output: (4, 3, 4)
input a2: (4, 3, 2, 1) output: (4, 3, 2, 1, 4)


## Exercises

$M_{ij} * B_{jk}$

$tr(M_{ij})$